build:
  image: yveshoppe/joomla-systemtests
  commands:
    - chmod a+x .drone/build.sh
    - ./.drone/build.sh
  clone:
    depth: 1
    path: repo
  notify:
    email:
      recipients:
        - yves@compojoom.com
        - daniel@copojoom.com
        - robert@rdeutz.de
      on_success: author
          on_failure: author
          