CREATE TABLE IF NOT EXISTS `#__cmc_lists` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `mc_id` varchar(10) NOT NULL,
  `web_id` int(11) NOT NULL,
  `list_name` varchar(255) NOT NULL,
  `date_created` datetime NOT NULL,
  `email_type_option` tinyint(1) NOT NULL DEFAULT '0',
  `use_awesomebar` tinyint(1) NOT NULL DEFAULT '1',
  `default_from_name` varchar(255) NOT NULL,
  `default_from_email` varchar(255) NOT NULL,
  `default_subject` varchar(255) DEFAULT NULL,
  `default_language` varchar(10) NOT NULL DEFAULT 'en',
  `list_rating` float(5,4) NOT NULL DEFAULT '0.0000',
  `subscribe_url_short` varchar(255) NOT NULL,
  `subscribe_url_long` varchar(255) NOT NULL,
  `beamer_address` varchar(255) NOT NULL,
  `visibility` varchar(255) NOT NULL DEFAULT 'pub',
  `created_user_id` int(11) NOT NULL,
  `created_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_user_id` int(11) NOT NULL,
  `modified_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `access` int(10) NOT NULL DEFAULT '0',
  `query_data` text,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `#__cmc_users` (
  `id` INT( 11 ) NOT NULL AUTO_INCREMENT,
  `mc_id` VARCHAR( 255 ) NULL ,
  `list_id` VARCHAR( 255 ) NOT NULL ,
  `firstname` VARCHAR( 255 ) NULL ,
  `lastname` VARCHAR( 500 ) NULL ,
  `email` VARCHAR( 500 ) NOT NULL ,
  `email_type` VARCHAR( 500 ) NULL ,
  `interests` TEXT NULL,
  `merges` TEXT NULL COMMENT 'json',
  `status` VARCHAR( 255 ) NOT NULL DEFAULT  'subscribed',
  `ip_signup` VARCHAR( 255 ) NULL ,
  `timestamp_signup` DATETIME NOT NULL ,
  `ip_opt` VARCHAR( 255 ) NULL ,
  `timestamp_opt` DATETIME NOT NULL ,
  `member_rating` TINYINT( 2 ) NOT NULL DEFAULT  '2',
  `campaign_id` INT( 11 ) NOT NULL ,
  `lists` VARCHAR( 255 ) NULL ,
  `timestamp` DATETIME NOT NULL ,
  `info_changed` DATETIME NOT NULL ,
  `web_id` VARCHAR( 255 ) NULL ,
  `is_gmonkey` TINYINT( 1 ) NOT NULL DEFAULT  '0',
  `geo` TEXT NULL COMMENT  'json',
  `clients` TEXT NULL COMMENT  'json',
  `static_segments` TEXT NULL COMMENT  'json',
  `created_user_id` INT( 11 ) NOT NULL ,
  `created_time` DATETIME NOT NULL ,
  `modified_user_id` INT( 11 ) NOT NULL ,
  `modified_time` DATETIME NOT NULL ,
  `query_data` TEXT NULL COMMENT  'json',
  PRIMARY KEY (`id`)
);
